# Generated by Django 5.1.2 on 2025-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('web_url', models.EmailField(max_length=254)),
                ('bussiness_name', models.CharField(max_length=250)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
