# Generated by Django 5.1.2 on 2025-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
