# Generated by Django 5.1.2 on 2025-05-07 15:52

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0002_restaurant_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True, prefix=''),
        ),
    ]
