# Generated by Django 5.1.2 on 2025-05-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0003_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
    ]
