# Generated by Django 5.1.2 on 2025-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0004_remove_restaurant_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
