# Generated by Django 5.1.2 on 2025-05-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0006_alter_restaurant_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
    ]
