# Generated by Django 5.0.14 on 2025-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0008_remove_restaurant_distance_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ambience',
            field=models.CharField(choices=[('casual', 'Casual'), ('family', 'Family'), ('fine_dining', 'Fine Dining'), ('outdoor', 'Outdoor'), ('romantic', 'Romantic')], default='casual', max_length=20),
        ),
    ]
