# Generated by Django 5.0.14 on 2025-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0009_restaurant_ambience'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.CharField(choices=[('none', 'No Delivery'), ('in_house', 'In-House Delivery')], default='none', max_length=20),
        ),
    ]
