# Generated by Django 5.1.2 on 2025-05-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0012_alter_restaurant_ambience_alter_restaurant_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_time', models.DateTimeField(auto_now_add=True)),
                ('selected_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantsModule.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
