# Generated by Django 5.1.2 on 2025-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0013_spinhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='xyz',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
