# Generated by Django 5.1.2 on 2025-05-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsModule', '0014_restaurant_xyz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='xyz',
        ),
    ]
